#!/bin/bash

shopt -s globstar

path=$(pwd)
verbose=1
recursive=0

while getopts 'qr' flag; do
	case "${flag}" in
		q) verbose=0 ;;
		r) recursive=1 ;;
		*) echo "Usage: $0 [-qr] PATH"; exit 1 ;;
	esac
done

if [[ $# -gt 0 ]]; then
	if [[ -d ${!#} ]]; then
		path=${!#}
	elif [[ -f ${!#} ]]; then
		path=${!#}
	fi
fi

function compress()
{
	if [[ -f $1 ]]; then
		bytes=$(wc -c "$1" | cut -f 1 -d ' '); level=0

		for i in {1..9}; do
			if [[ $(gzip -cf -$i "$1" | wc -c) -lt $bytes ]]; then
				bytes=$(gzip -cf -$i "$1" | wc -c); level=$i
			fi
		done

		if [[ $level -gt 0 ]]; then
			if [[ $verbose -gt 0 ]]; then
				echo "Gzipping $1 with compression level $level."
			fi

			$(gzip -cf -$level "$1" > "$1".gz && touch -r "$1" "$1.gz")
		elif [[ $verbose -gt 0 ]]; then
			echo "Skipping $1."
		fi
	fi
}

if [ -d "$path" ]; then
	for file in "$path"/*.{css,cur,eot,htc,html,ico,js,json,otf,svg,ttc,ttf,xml}; do
		compress "$file"
	done

	if [[ $recursive -gt 0 ]]; then
		for file in "$path"/**/*.{css,cur,eot,htc,html,ico,js,json,otf,svg,ttc,ttf,xml}; do
			compress "$file"
		done
	fi
elif [[ -f "$path" ]]; then
	compress "$path"
fi
