#!/bin/bash

if [[ $# -ne 1 ]]; then
    echo "Usage: n1ensite [site]" && exit 1
fi

if [[ -r /etc/nginx/sites-available/$1 ]]; then
    if [[ -h /etc/nginx/sites-enabled/$1 ]]; then
        echo "Site $1 already enabled." && exit 0
    else
        ( ln -s /etc/nginx/sites-available/$1 /etc/nginx/sites-enabled/$1 ) > /dev/null

        if [[ $? == 0 ]]; then
            echo -e "Enabling site $1.\nTo activate the new configuration, you need to run:\n  service nginx reload" && exit 0
        fi
    fi
else
    echo "ERROR: Site $1 does not exist!" && exit 1
fi
